#!/bin/bash

: "${BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR:="$HOME/Downloads/firefox"}"
: "${BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR:=}"

: "${BUBBLEJAIL_WRAPPER_FIREFOX_EXTRA_ARGS:=}"
: "${BUBBLEJAIL_WRAPPER_FIREFOX_CMD:=firefox}"

bubblejail_args=
_bwrap_args=
_firefox_args=

# profile. use an empty profile by default, mount user's profile if requested
if [ -z "$BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR" ]; then
	_bwrap_args="--tmpfs $HOME/Downloads"
	# don't accept requests from other applications
	_firefox_args="--no-remote"
else
	bubblejail_args+=" --rw $HOME/.mozilla/firefox/profiles.ini"
	bubblejail_args+=" --rw $BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR"
	_firefox_args+=" --profile $BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR"
fi

# persistent download dir
if [ "$BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR" ]; then
	mkdir -p "$BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR"
	_bwrap_args+=" --bind $BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR $HOME/Downloads"
fi

#shellcheck disable=SC2086
exec bubblejail \
	--x11 \
	--need-devfs \
	--need-procfs \
	--share-net \
	--need-dns \
	--need-env-vars "HOME" \
	$bubblejail_args \
	$BUBBLEJAIL_WRAPPER_FIREFOX_EXTRA_ARGS \
	$_bwrap_args \
	$BUBBLEJAIL_WRAPPER_FIREFOX_CMD \
	$_firefox_args \
	"$@"
