#!/bin/bash

: "${BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR:="$HOME/Downloads/firefox"}"
: "${BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR:=}"

: "${BUBBLEJAIL_WRAPPER_FIREFOX_EXTRA_ARGS:=}"
: "${BUBBLEJAIL_WRAPPER_FIREFOX_CMD:=firefox}"

_extra=
_args=

# persistent download dir
if [ "$BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR" ]; then
	mkdir -p "$BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR"
	_extra+=" --rw $BUBBLEJAIL_WRAPPER_FIREFOX_DOWNLOADS_DIR"
fi

# use an empty profile by default, bind user's profile on demand
if [ -z "$BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR" ]; then
	# don't accept requests from other applications
	_args="--no-remote"
else
	# mount profile related paths
	_extra+=" --rw $HOME/.mozilla/firefox/profiles.ini"
	_extra+=" --rw $BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR"
	# force firefox to use that profile
	_args="--profile $BUBBLEJAIL_WRAPPER_FIREFOX_PROFILE_DIR"
fi

#shellcheck disable=SC2086
exec bubblejail \
	--x11 \
	--need-dev \
	--need-proc \
	--need-netns \
	--need-env-vars "HOME" \
	$_extra \
	$BUBBLEJAIL_WRAPPER_FIREFOX_EXTRA_ARGS \
	$BUBBLEJAIL_WRAPPER_FIREFOX_CMD \
		$_args \
		"$@"
