#!/bin/sh

#FIXME: can't join calls, probably needs dbus/pulseaudio magic

mkdir -p "$HOME/Downloads/teams"

#shellcheck disable=SC2086
exec bubblejail \
	--x11 \
	--need-dev \
	--need-proc \
	--need-netns \
	--need-env-vars "HOME TZ" \
	--rw "$HOME/Downloads/teams" \
	--rw "$HOME/.config/Microsoft/" \
	"--ro-bind-try /etc/localtime /etc/localtime" \
	$BUBBLEJAIL_WRAPPER_TEAMS_EXTRA_ARGS \
	${BUBBLEJAIL_WRAPPER_TEAMS_CMD:-teams} "$@"
